trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*
  paths:
    include:
    - '*'
    exclude:
    - README.md
    - docs/*
pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - README.md
    - docs/*

pool: 
  vmImage: 'macOS-10.14'
steps:
  - checkout: self
    submodules: true
  - script: git clone --recursive --branch android https://github.com/daquexian/onnxruntime $(Agent.HomeDirectory)/onnxruntime
    displayName: Clone ONNX Runtime
  - script: rm -rf $(Agent.HomeDirectory)/onnxruntime/cmake/external/DNNLibrary && cp -r $(Build.SourcesDirectory) $(Agent.HomeDirectory)/onnxruntime/cmake/external/DNNLibrary
    displayName: Copy latest DNNLibrary
  - script: pip install cmake==3.13.2.post1 && alias cmake=/usr/local/bin/cmake && cmake --version && brew install coreutils
    displayName: Install cmake 3.13 and coreutils
  - script: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'ndk-bundle'
    displayName: Install Android NDK
  - script: tools/ci_build/build.py --android --build_dir build --android_ndk $ANDROID_HOME/ndk-bundle --android_abi=x86_64 --skip_submodule_sync --parallel --use_dnnlibrary
    workingDirectory: $(Agent.HomeDirectory)/onnxruntime
    displayName: Build and Test on Android Emulator
